global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: api-gateway
    static_configs:
      - targets: ["api-gateway:8080"]
    metrics_path: /metrics

  - job_name: auth-service
    static_configs:
      - targets: ["auth-service:8081"]
    metrics_path: /metrics

  - job_name: upload-service
    static_configs:
      - targets: ["upload-service:8082"]
    metrics_path: /metrics

  - job_name: status-service
    static_configs:
      - targets: ["status-service:8083"]
    metrics_path: /metrics

  - job_name: rabbitmq
    static_configs:
      - targets: ["rabbitmq:15692"]
    metrics_path: /metrics
