apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: fiapx
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: ghcr.io/mechmanager/fiapx-notification-service:latest
          envFrom:
            - configMapRef:
                name: fiapx-notification-config
          env:
            - name: POSTGRES_DSN
              value: postgres://fiapx:fiapx123@postgres:5432/fiapx?sslmode=disable
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: fiapx-shared
                  key: POSTGRES_USER
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: fiapx-shared
                  key: POSTGRES_DB
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fiapx-secrets
                  key: postgres-password
            - name: RABBITMQ_URL
              value: amqp://fiapx:fiapx123@rabbitmq:5672/
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fiapx-secrets
                  key: rabbitmq-password
            - name: SMTP_PASS
              valueFrom:
                secretKeyRef:
                  name: fiapx-secrets
                  key: smtp-password
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
