name: sonar

on:
  push:
    branches: [main, develop]

jobs:
  sonar:
    name: SonarCloud
    runs-on: ubuntu-latest
    env:
      GO_VERSION: "1.25"
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          fetch-depth: 0

      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Gerar relatórios de cobertura
        run: |
          cd api-gateway       && go test -coverprofile=coverage.out ./config/... ./middleware/... ./proxy/...       && cd ..
          cd auth-service      && go test -coverprofile=coverage.out ./config/...                                        && cd ..
          cd upload-service    && go test -coverprofile=coverage.out ./config/... ./domain/... ./service/... ./handler/... && cd ..
          cd status-service    && go test -coverprofile=coverage.out ./config/... ./domain/... ./service/... ./handler/... && cd ..
          cd notification-service && go test -coverprofile=coverage.out ./config/... ./domain/... ./mailer/... && cd ..
          cd worker            && go test -coverprofile=coverage.out ./config/... ./pipeline/... ./processor/...               && cd ..

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@ba3875ecf642b2129de2b589510c81a8b53dbf4e
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
